name: DOTNET PIPELINE
on:
  push:
    branches:
     - master
jobs:
  dotnet-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: requirements
      run: pip install -r requirements.txt

    - name: python file
      run: python detnet.py

    - name: python version
      run: python --version

