name: INSTALL PYTHON
on:
  push:
    branches:
     - master
jobs:
  python-job:
    runs-on: ubuntu-latest

    steps:
    - name: CHECKOUT REPO
      uses: actions/checkout@v4

    - name: SET-UP PYTHON
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: INSTALL PYTHON DEPENDENCIES
      run: pip install -r requirements.txt

    - name: RUN PYTHON FILE
      run: python text.txt

    - name: run python file
      run: python hello.py

    - name: PYTHON VERSION
      run: python --version
      
