name: INSTALL PYTHON
on:
  push:
    branches:
     - master
jobs:
  python-job:
    runs-on: ubuntu-latest

    steps:
    - name: CHECKOUT REPO
      uses: actions/checkout@v4

    - name: SET-UP PYTHON
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: RUN PYTHON
      run: python test.txt

    - name: PYTHON VERSION
      run: python --version
      
